### ISSUE TITLE
Store Inventory Bug

### ISSUE THREAD

**Issue by djlawrence4** [graywolf336/Jail#118]
Greywolf336 I have finished my testing. The following I have done

- Fresh server with fresh plugin install (Vault and Jail only!)
- Fresh Jail / Cell creation
- Using Java 8
- On windows and linux platform
- Changes in the config (store inventory)

I found the source of the issue. When you have store inventory feature turned on and using a chest it will duplicate the gear. When the player is jailed and the inventory is moved to the chest during that transfer the gear gets duplicated only if the gear is equipped. When you open the chest you now notice that there are two sets of gear in the chest.  After the player is unjailed they now have one set of gear equipped and another in their inventory.

But if the player has gear in the inventory and not equipped when jailed only one set of gear will be in the chest. After you unjail the player the gear is now equipped when it was originally in the inventory. 

Also when the player is wearing a shield in their offhand before jail... after jail it is now on their actionbar or inventory.

If the player has a full inventory with an item in their offhand and gear equipped, after they are released their offhand item will drop along with a set of duplicated gear in the cell because their wasn't enough room in their inventory.

Not using the store feature everything works well and fine. I know not much about code but it could be because spigot changed the way that inventory is handled in 1.9

Hopefully this explains it well. I still have my test server stored let me know if you want me to try anything else.

**Comment by graywolf336** [comment]
Yes, this is due to how 1.9 changed inventory handling. They now include the armor in the `player.getInventory()` whereas before they weren't and since in the past they didn't, we made a call to get it. But now that the armor is included, we're making two calls and storing it twice thus returning it twice.

As far as replacing the items in their inventory back to where it was, I won't be implementing it *however* anyone else out there is free to submit a pull request to this project since it is open source. :+1:

**Comment by graywolf336** [comment]
@djlawrence4 Can you confirm the fix actually fixed this?

**Comment by djlawrence4** [comment]
Confirmed fixed

**Comment by graywolf336** [comment]
Thanks
